const steps = ["entity","safe","elections","entitypack","jurisdiction","gir"];
const stepMeta = {
  entity:{title:"Entity Administration",doc:"Entity Administration - Version CW",tree:"Entity Administration - Version CW",flow:"Entity Admin → WData → Safe Harbour",instructionTitle:"Start with the entity source of truth",instructionCopy:"Review the entity table. When ready, open the Outgoing tab and share updates so the data is available in WData.",incoming:"General lists incoming",outgoing:"Entity administration data points - WData",tip:"In Workiva, sharing the outgoing connection is the hand-off to WData. This action is required before the next spreadsheet can reuse the data."},
  safe:{title:"Transitional Safe Harbour",doc:"2024 - Pillar 2 - Transitional Safe Harbour",tree:"2024 - Pillar 2 - Transitional Safe Harbour",flow:"Entity Admin + Financial Data → Safe Harbour → WData",instructionTitle:"Review the Safe Harbour tests",instructionCopy:"Scroll horizontally through the calculation columns. Change a value if you want, then share the outgoing Safe Harbour connection.",incoming:"Entity Registration + CbCR data",outgoing:"Safe Harbour - 2024",tip:"The important branching moment is the overall Safe Harbour result. A failed jurisdiction activates the Entity Pack and Jurisdictional Pack steps."},
  elections:{title:"Jurisdictional Elections",doc:"Year - Jurisdictional Elections",tree:"Jurisdictional Election Template",flow:"Entity Registration → Elections → WData",instructionTitle:"Capture jurisdictional elections",instructionCopy:"Review annual and five-year election dropdowns by jurisdiction. Then share Outgoing Elections to WData.",incoming:"Incoming Entity Registration",outgoing:"Outgoing Elections",tip:"Election selections are captured once and reused later in the Entity Pack, Jurisdictional Pack and GIR."},
  entitypack:{title:"Entity Pack",doc:"Pillar 2 - Entity Pack",tree:"Pillar 2 - Entity Pack",flow:"Failed Safe Harbour entities → Entity Pack → WData",instructionTitle:"Complete the Entity Pack for failed entities",instructionCopy:"This step is only required because the Netherlands Safe Harbour test failed. Review automated amounts and user adjustment columns, then share Entity Data.",incoming:"Entity Registration + Safe Harbour + Elections",outgoing:"Outgoing Entity Data",tip:"Green cells represent automated data. Blue cells are user-provided additions or reductions. The pack calculates net totals and stores reporting data points for later aggregation."},
  jurisdiction:{title:"Jurisdictional Pack",doc:"Jurisdictional Pack",tree:"Jurisdictional Pack",flow:"Entity Packs → Jurisdictional aggregation → WData",instructionTitle:"Aggregate entity results at jurisdiction level",instructionCopy:"Review the automated jurisdiction summary, including GloBE Income, covered taxes, ETR and top-up tax. Then share the jurisdiction output.",incoming:"Entity Pack outputs + Elections",outgoing:"Outgoing Jurisdiction Data",tip:"Multiple entity packs in the same jurisdiction are aggregated here. This produces the jurisdiction-level values required for the final return."},
  gir:{title:"GIR – Global",doc:"GIR - Global",tree:"GIR - Global",flow:"Entity + Jurisdiction data → GIR-ready dataset",instructionTitle:"Review the Global Information Return dataset",instructionCopy:"The final GIR view combines entity-level and jurisdiction-level information. This demo stops at a prepared reporting dataset; it does not simulate regulatory submission.",incoming:"Entity + Jurisdiction + Election outputs",outgoing:"Final GIR dataset",tip:"The solution prepares the relevant data points for downstream tagging or filing. Actual authority submission and production tagging are outside this demo."}
};

const state={current:"entity",shared:new Set(),safeFail:true,modalIndex:0};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.remove("hidden");setTimeout(()=>t.classList.add("hidden"),2600)}
function letters(n){return Array.from({length:n},(_,i)=>String.fromCharCode(65+i))}
function row(cells,cls=""){return `<tr class="${cls}"><td class="rownum"></td>${cells.map(c=>`<td class="${c.cls||""}" ${c.colspan?`colspan="${c.colspan}"`:""}>${c.html??c}</td>`).join("")}</tr>`}
function makeTable(headers,rows,width=headers.length){let html=`<thead><tr class="letters"><th class="rownum"></th>${letters(width).map(x=>`<th>${x}</th>`).join("")}</tr><tr><th class="rownum">1</th>${headers.map(h=>`<th class="${h.cls||"section-head"}">${h.html??h}</th>`).join("")}</tr></thead><tbody>`;rows.forEach((r,i)=>{html+=r.replace('<td class="rownum"></td>',`<td class="rownum">${i+2}</td>`)});return html+"</tbody>"}
function input(value,type="number",cls=""){return `<input class="${cls}" type="${type}" value="${value}" />`}
function sel(values,selected){return `<select>${values.map(v=>`<option ${v===selected?"selected":""}>${v}</option>`).join("")}</select>`}

function entityTable(){const headers=["Fiscal Year","Entity Code","Entity Name","Joined or left the MNE group during year","Part of the group as of day","Part of the group until this day","TIN","UPE only yes where relevant","Pope Indicator","Jurisdiction","Parent Entity","Shareholder"];
const entities=[[2024,111,"O Sarl","","","","TIO","","No","Netherlands","ATC Holding BV","ATC Holding BV"],[2024,103,"P Sarl","","","","TIP","","No","France","ATC Holding BV","ATC Holding BV"],[2024,101,"A BV","","","","TIA","yes","No","Netherlands","ATC Holding BV","ATC Holding BV"],[2024,107,"B BV","","","","TIB","","No","Netherlands","ATC Holding BV","ATC Holding BV"],[2024,109,"C BV","","","","TIC","","No","UK","ATC Holding BV","ATC Holding BV"],[2024,108,"Q SARL","","","","TIQ","","No","France","ATC Holding BV","ATC Holding BV"],[2024,117,"R SARL","","","","TIR","","No","UK","ATC Holding BV","ATC Holding BV"],[2024,119,"D BV","","","","TID","","No","Netherlands","ATC Holding BV","ATC Holding BV"],[2024,105,"E BV","","","","TIE","","No","UK","ATC Holding BV","ATC Holding BV"]];
return makeTable(headers,entities.map(e=>row(e.map((v,i)=>({html:i===9?sel(["Netherlands","France","UK"],v):v,cls:i>=1?"manual":""})))),headers.length)}
function safeTable(){const headers=["Result of PY Safe Harbour Test","#","Jurisdiction ID","Fiscal year","Revenue (CbCr)","ADJ 1","ADJ 2","ADJ 3","Revenue for Pillar 2","Profit (loss) before income tax (CbCr)","ADJ 1","ADJ 2","ADJ 3","Profit before income tax for Pillar 2","Income tax expense","ETR","Employee Expenses","Tangible Assets","Substance-based income exclusion","De minimis Test","Simplified ETR Test","Routine profit Test","Safe harbour applicable","Which one do you choose?"];
const jurisdictions=[{j:"Netherlands - CE -",rev:2000000,profit:1000000,tax:140000,etr:"14.00%",sbie:158293,tests:["Fail","Fail","Fail","Fail"],choice:""},{j:"France - CE -",rev:3000000,profit:17800000,tax:5000000,etr:"28.09%",sbie:"—",tests:["Fail","Pass","Fail","Pass"],choice:"Simplified ETR Test"},{j:"UK - CE -",rev:1900000000,profit:20000000,tax:1200000,etr:"6.00%",sbie:"—",tests:["Fail","Fail","Fail","Fail"],choice:""}];
const rows=jurisdictions.map((x,i)=>{const test=x.tests;return row([{html:i===0?"New jurisdiction":"New jurisdiction",cls:"total"},{html:i+1},{html:sel(["Netherlands - CE -","France - CE -","UK - CE -"],x.j),cls:"manual"},{html:2024,cls:"total"},{html:input(x.rev),cls:"auto"},{html:"",cls:"manual"},{html:"",cls:"manual"},{html:"",cls:"manual"},{html:x.rev.toLocaleString(),cls:"total"},{html:input(x.profit),cls:"auto"},{html:"",cls:"manual"},{html:"",cls:"manual"},{html:"",cls:"manual"},{html:x.profit.toLocaleString(),cls:"total"},{html:input(x.tax),cls:"auto"},{html:x.etr,cls:"total"},{html:i===0?"300,000":"",cls:"auto"},{html:"",cls:"auto"},{html:x.sbie,cls:"total"},...test.map(v=>({html:v,cls:v==="Pass"?"pass":"fail"})),{html:x.choice,cls:"total"}])});
return makeTable(headers,rows,headers.length)}
function electionsTable(){const headers=["Year for which the elections are made","Jurisdiction ID","Aggregate asset gain election (Article 3.2.6)","Immaterial decrease in Covered Taxes election (Article 4.6.1)","Election not to apply the Substance-based Income Exclusion (Article 5.3.1)","Negative Tax Expense Carry-forward (Article 4.1.5)","Deemed Distribution election","Equity Investment Inclusion Election (Article 3.2.1(c))","Election year","Revocation Year","Notification","Stock-based compensation election"];
const j=["Netherlands - CE -","France - CE -","UK - CE -"];const rows=j.map((x,i)=>row([{html:2024},{html:sel(j,x)},{html:sel(["No","Yes"],"No"),cls:"manual"},{html:sel(["No","Yes"],"No"),cls:"manual"},{html:sel(["No","Yes"],"No"),cls:"manual"},{html:sel(["No","Yes"],"No"),cls:"manual"},{html:sel(["No","Yes"],"No"),cls:"manual"},{html:sel(["No","Yes"],"No"),cls:"manual"},{html:"",cls:"manual"},{html:"",cls:"manual"},{html:"",cls:"total"},{html:sel(["No","Yes"],"No"),cls:"manual"}]));return makeTable(headers,rows,headers.length)}
function entityPackTable(){const headers=["OECD GIR number","Reference","Description","Instructions","Automated Additions","Automated Reductions","Please provide + amounts","Please provide - amounts","Net total amounts","Check for correct field entry","Check for correct figure entry"];
const rows=[row([{html:""},{html:"3.1.1"},{html:"<strong>GloBE Income Calculation</strong>"},{html:""},{html:"",cls:"auto"},{html:"",cls:"auto"},{html:input(1215000),cls:"manual"},{html:"",cls:"manual"},{html:"1,215,000",cls:"total"},{html:"✓"},{html:"✓"}]),row([{html:""},{html:"3.1.1"},{html:"Adjustments to determine Final according to GloBE tax before allocations"},{html:""},{html:"",cls:"auto"},{html:"",cls:"auto"},{html:"",cls:"manual"},{html:"",cls:"manual"},{html:"—",cls:"total"},{html:"✓"},{html:"✓"}]),row([{html:""},{html:"3.1.1"},{html:"Include / exclude topside adjustment related to one jurisdiction but accounted in another jurisdiction"},{html:""},{html:"",cls:"auto"},{html:"",cls:"auto"},{html:"",cls:"manual"},{html:"",cls:"manual"},{html:"—",cls:"total"},{html:"✓"},{html:"✓"}]),row([{html:"3.2.4.1.a.3.a"},{html:"3.2.1 (a) & 10.1"},{html:"<strong>Net Tax Expense</strong> – Exclude Net taxes expense"},{html:""},{html:"",cls:"auto"},{html:"",cls:"auto"},{html:input(35000),cls:"manual"},{html:"",cls:"manual"},{html:"35,000",cls:"total"},{html:"✓"},{html:"✓"}]),row([{html:""},{html:""},{html:"Allocation of GloBE income/loss related to Permanent establishments and flow through entities"},{html:""},{html:"",cls:"auto"},{html:"",cls:"auto"},{html:"",cls:"manual"},{html:"",cls:"manual"},{html:"—",cls:"total"},{html:"✓"},{html:"✓"}])];return makeTable(headers,rows,headers.length)}
function jurisdictionTable(){const headers=["General Jurisdiction Information","Value","Input type","Pillar II Calculation Summary","Amounts in EUR","Source"];
const rows=[row([{html:"Jurisdiction Name"},{html:"UK",cls:"total"},{html:"Automated"},{html:"GloBE Income (+ = profit / - = loss)"},{html:"20,700,000",cls:"total"},{html:"Automated"}]),row([{html:"Jurisdiction ID"},{html:sel(["UK - CE -","Netherlands - CE -"],"UK - CE -"),cls:"manual"},{html:"Select"},{html:"Covered taxes (+ = expense / - = profit)"},{html:"1,210,000",cls:"total"},{html:"Automated"}]),row([{html:"Year"},{html:"2024",cls:"total"},{html:"Automated"},{html:"Substance Based Income Exclusion"},{html:"29,400",cls:"total"},{html:"Automated"}]),row([{html:"Reporting Currency"},{html:"EUR",cls:"total"},{html:""},{html:"Excess Profit"},{html:"20,670,600",cls:"total"},{html:"Automated"}]),row([{html:"Transitional Safe Harbour applicable"},{html:"Test failed",cls:"fail"},{html:"Automated"},{html:"Top-up tax"},{html:"1,889,309",cls:"total"},{html:"Automated"}]),row([{html:"Subgroup type"},{html:"Joint Venture Group",cls:"total"},{html:""},{html:"Top up tax payable"},{html:"1,889,309",cls:"total"},{html:"Automated"}]),row([{html:"TIN Subgroup"},{html:"TIZ",cls:"total"},{html:""},{html:"ETR in %"},{html:"5.85%",cls:"fail"},{html:"Automated"}])];return makeTable(headers,rows,headers.length)}
function girTable(){const headers=["1.1 Identification of the Filing Constituent Entity","Value","1.2 MNE Group General Information","Value","1.3 Corporate Structure","Value","Chapter / status"];
const rows=[row([{html:"UPE is the Filing Constituent Entity"},{html:sel(["Yes","No"],"Yes"),cls:"manual"},{html:"Name of the MNE Group"},{html:"ATS JV SARL",cls:"manual"},{html:"Name of the UPE"},{html:"ATC Holding BV",cls:"manual"},{html:"Chapter 1"}]),row([{html:"Name of the Filing Constituent Entity"},{html:"ATC Holding BV",cls:"manual"},{html:"Start date of Reporting Fiscal Year"},{html:"2024-01-01",cls:"total"},{html:"TIN of the UPE"},{html:"atch123",cls:"total"},{html:"1.1 / 1.2"}]),row([{html:"Tax identification number (TIN)"},{html:"atch123",cls:"total"},{html:"End date of Reporting Fiscal Year"},{html:"2024-12-31",cls:"total"},{html:"Status for GloBE purposes"},{html:"Constituent Entity",cls:"total"},{html:"1.3"}]),row([{html:"Role"},{html:sel(["Ultimate Parent Entity","Designated Filing Entity"],"Ultimate Parent Entity"),cls:"manual"},{html:"Amended Return"},{html:sel(["Choose","No","Yes"],"Choose"),cls:"manual"},{html:"Applicable rules?"},{html:sel(["Choose","Yes","No"],"Choose"),cls:"manual"},{html:"Chapter 2 / 3"}]),row([{html:"Jurisdiction where the Filing CE is located"},{html:"Netherlands",cls:"total"},{html:"Financial Accounting Standard"},{html:"IFRS",cls:"manual"},{html:"ETR computation"},{html:"5.85%",cls:"auto"},{html:"3.2 ETR computation"}])];return makeTable(headers,rows,headers.length)}
function tableFor(step){return ({entity:entityTable,safe:safeTable,elections:electionsTable,entitypack:entityPackTable,jurisdiction:jurisdictionTable,gir:girTable})[step]()}
function treeFor(step){const maps={entity:["Entity administration data points - WData","General lists incoming","Dropdown"],safe:["Safe harbour - Jurisdictions","Jurisdiction Validation","Data","Safe Harbour outgoing","Entity Registration","Safe Harbour PY","Lists","CbCr data"],elections:["Jurisdictional Election Template","Outgoing Elections","Incoming Entity Registration"],entitypack:["Health sheet","1 - General Information","2a - Jurisdictional Elections","2b - Entity elections","3 - GloBE Income or Loss","3a - Allocations related to…","3b - Cross-border adjustments","4 - Covered Taxes","5 - Substance Based Income…","6 GIR-Report","Admin","Outgoing Entity Data","Incoming Entity Registration"],jurisdiction:["1 - General Information","1a - Characteristics of the…","1b - Other Accounting Standards","1c - High summary","1d - Jurisdiction Elections","2 - GloBE Income & Loss","3 - Covered Taxes","4 - Substance based income…","5 - Top-up Tax Calculation","Allocation if needed","Additional top up tax"],gir:["Chapter 1 - General information","1.1 - Filing Constituent Entity","1.1 Recipient Jurisdiction","1.3.2 Group entities","1.3.3 Changes in structure","1.4 High level summary","Chapter 2 - Jurisdictional…","2.2 Jurisdictional exceptions","Chapter 3 - GloBE Computation","3.2 ETR computation"]};return maps[step].map((x,i)=>`<div class="tree-item ${i===0||x.startsWith('Chapter')||/^\d -/.test(x)?'group':''} ${i===0?'selected':''}"><span>${i===0?'⌄ ':''}${x}</span>${i%3===0?'<span class="tree-status"></span>':''}</div>`).join("")}
function renderConnections(){const m=stepMeta[state.current];const shared=state.shared.has(state.current);$("#incoming-panel").innerHTML=`<div class="connection-note">Incoming data is refreshed from previously shared WData outputs.</div><article class="connection-card"><div class="connection-card-head"><strong>${m.incoming}</strong><span>↻</span></div><p>Source: <a>WData</a> · Table<br><b style="color:#299337">✓</b> Last refreshed: ${state.current==='entity'?'Demo baseline':'Just now'}</p></article>`;$("#outgoing-panel").innerHTML=`<div class="connection-note">Share updates to push the latest spreadsheet values into WData.</div><article class="connection-card" id="outgoing-card"><div class="connection-card-head"><strong>${m.outgoing}</strong><span class="share-arrow">↑</span></div><p>Destination: <a>WData</a> · Table<br><span id="last-shared">${shared?'✓ Last shared: Just now':'○ Updates not yet shared'}</span></p><button id="share-updates" class="share-button ${shared?'shared':''}" type="button">${shared?'✓ Updates shared':'↑ Share updates'}</button></article>`;$("#share-updates")?.addEventListener("click",shareCurrent)}
function setConnectionTab(tab){const incoming=tab==='incoming';$("#incoming-tab").classList.toggle("active",incoming);$("#outgoing-tab").classList.toggle("active",!incoming);$("#incoming-panel").classList.toggle("hidden",!incoming);$("#outgoing-panel").classList.toggle("hidden",incoming)}
function showStep(step){if(!steps.includes(step))return;if($(`.step-button[data-step="${step}"]`).classList.contains("locked")){toast("Complete and share the earlier steps first.");return}state.current=step;const i=steps.indexOf(step),m=stepMeta[step];$("#page-title").textContent=m.title;$("#doc-title").textContent=m.doc;$("#tree-title").textContent=m.tree;$("#tree-items").innerHTML=treeFor(step);$("#sheet-table").innerHTML=tableFor(step);$("#instruction-number").textContent=i+1;$("#instruction-title").textContent=m.instructionTitle;$("#instruction-copy").textContent=m.instructionCopy;$("#flow-note").textContent=m.flow;$("#progress-text").textContent=`Step ${i+1} of 6`;$("#progress-bar").style.width=`${((i+1)/6)*100}%`;$$('.step-button').forEach(b=>b.classList.toggle('active',b.dataset.step===step));$("#step-status").textContent=state.shared.has(step)?"Shared to WData":"Not shared";$("#step-status").classList.toggle("shared",state.shared.has(step));$("#previous-step").disabled=i===0;$("#next-step").textContent=i===5?"Demo complete ✓":"Next step →";$("#next-step").disabled=!state.shared.has(step)&&step!=="gir";setConnectionTab('incoming');renderConnections();$("#sheet-scroll").scrollLeft=0;bindDynamicInputs();}
function bindDynamicInputs(){if(state.current==='safe'){$$('#sheet-table input').forEach(inp=>inp.addEventListener('change',()=>{const first=[...$('#sheet-table tbody tr').children];}));}}
function shareCurrent(){if(state.current==='safe'){const firstRow=$('#sheet-table tbody tr');const inputs=firstRow.querySelectorAll('input');const profit=Number(inputs[1]?.value||1000000);const tax=Number(inputs[2]?.value||140000);const etr=profit?tax/profit:0;const cells=firstRow.querySelectorAll('td');const testCells=[...cells].slice(-5,-1);const simplified=etr>=.15;const pass=simplified || Number(inputs[0]?.value||2000000)<10000000;state.safeFail=!pass;testCells[1].textContent=simplified?'Pass':'Fail';testCells[1].className=simplified?'pass':'fail';testCells[3].textContent=pass?'Pass':'Fail';testCells[3].className=pass?'pass':'fail';}
state.shared.add(state.current);$(`.step-button[data-step="${state.current}"]`).classList.add('complete');if(state.current==='safe'&&!state.safeFail){toast("Safe Harbour passed. Entity Pack is not required for this jurisdiction. For the demo, Netherlands remains configured as the failed path.");state.safeFail=true;}
unlockNext();renderConnections();$("#step-status").textContent="Shared to WData";$("#step-status").classList.add('shared');$("#next-step").disabled=false;updateWData();toast(`${stepMeta[state.current].title} updates shared to WData.`);}
function unlockNext(){const i=steps.indexOf(state.current);if(i<steps.length-1){const next=steps[i+1];const btn=$(`.step-button[data-step="${next}"]`);if(state.current==='elections'||state.current==='entitypack'||state.current==='jurisdiction'||state.current==='entity'||state.current==='safe')btn.classList.remove('locked');}if(state.shared.has('safe')&&state.safeFail)$(`.step-button[data-step="entitypack"]`).classList.remove('locked');}
function updateWData(){const list=$('#wdata-list');if(!state.shared.size){list.innerHTML='<li class="empty">No updates shared yet.</li>';return}list.innerHTML=steps.filter(s=>state.shared.has(s)).map(s=>`<li>✓ ${stepMeta[s].title}</li>`).join('')}
function nextStep(){const i=steps.indexOf(state.current);if(i===5){toast("Demo complete. GIR-ready data has been assembled.");return}const next=steps[i+1];showStep(next);showGuide(i+1)}function prevStep(){const i=steps.indexOf(state.current);if(i>0)showStep(steps[i-1])}
function showGuide(index=steps.indexOf(state.current)){state.modalIndex=index;const step=steps[index],m=stepMeta[step];$('#modal-step').textContent=`STEP ${index+1} OF 6`;$('#modal-title').textContent=m.title;$('#modal-copy').textContent=m.instructionCopy;$('#modal-tip').textContent=m.tip;$('#modal-back').style.visibility=index===0?'hidden':'visible';$('#modal-next').textContent=index===5?'Close':'Got it';$('#modal').classList.remove('hidden')}
function highlightOutgoing(){setConnectionTab('outgoing');const card=$('#outgoing-card');card?.classList.add('highlight');setTimeout(()=>card?.classList.remove('highlight'),4500)}
function restart(){state.current='entity';state.shared.clear();state.safeFail=true;$$('.step-button').forEach((b,i)=>{b.classList.remove('complete','locked');if(i>0)b.classList.add('locked')});updateWData();showStep('entity');showGuide(0)}
$('#incoming-tab').addEventListener('click',()=>setConnectionTab('incoming'));$('#outgoing-tab').addEventListener('click',()=>setConnectionTab('outgoing'));$('#instruction-action').addEventListener('click',highlightOutgoing);$('#next-step').addEventListener('click',nextStep);$('#previous-step').addEventListener('click',prevStep);$('#restart-demo').addEventListener('click',restart);$('#show-help').addEventListener('click',()=>showGuide());$('#modal-close').addEventListener('click',()=>$('#modal').classList.add('hidden'));$('#modal-next').addEventListener('click',()=>$('#modal').classList.add('hidden'));$('#modal-back').addEventListener('click',()=>{if(state.modalIndex>0){state.modalIndex--;showGuide(state.modalIndex)}});$$('.step-button').forEach(b=>b.addEventListener('click',()=>showStep(b.dataset.step)));
showStep('entity');setTimeout(()=>showGuide(0),350);
